spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:~/todo
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

